language: generic
sudo: required
services: docker
branches:
  only:
  - master
env:
  global:
  - PROJECT_NAME=lpp-account
  - PROJECT_VERSION=1.0.3
  - DOCKER_USERNAME=bezpov
  - secure: EX/0cLRBnBvBJxNy97PLAIuhPJmzXNvx1dBXAAqulWowehpCWEoJx7Wsyr2DYggLaCr8g1ILVy/djzAMyPuy4IjpIMVT7G3Cu+BlLV8lw9qMbGriJYVu6nv7/mwgII/S15JEDWoHr7+Ts+cxRbA5N9n0jfhUKjsbL2XdIRur/32yJYcK6Xcxpi5l3oBo7PdLIE7l97dbDkl3C7u+Ql/tNQLRAZqge/sXXK8oeLkX+4MVRR3qTpcUQ7cWzDsg1x9z3bHO7qUmPK01Quk5S6JO3PkQJQiY98KVSz3jU3ii4JYrCsM/EEUoSLgFUd6Xj4mbvFErGFmxUy4EEq6eRLXFh7JfFc7TwIEOovEF49SloZX+7My1fBCDOrgizE31dHPOvZEDlvHBhyLif6vtW5i3WLvc1TAMqI9xanvd07ZBvyU7nxv9TIgtkHFZ2yOwrZWlCoKnGOXRW630Hh8h4/O4UU8Hz5wI+EnDbrzikTlcP58n3w0i4SDHms6muSlIuUGBaOlPELPidzMQse4EyAV9sBP8XQF8cn/aW48C2tfEIczylA4km4TYnbxDUoxaVQEIyl2I/IamMfi5YS5Ps4djhfzEIF2RNh2PWEHkBf4dPwWsZgSJC71nw7kZvKgHS6P177CKfbQOG2XkRFWw4DdyKlohgDyDgrKm0gnpyo/dP/U=
  - secure: bsI+tNxcP1HGHkDjJ8hfNjHGCbUWfM5oU8IPnyolDk5Wf1itql0pdu+U2cV/rYO8rFUTLtt7PTstFPdNUHL9Rphy9oHeWnhuQe77pZYWlCTl7URsioQJybpD9e678tqnF3nE2MDK3I9PueJisZ4lrZ1CO6d9fTcwJmmmsWkUP1g8vk+NZdp9k3auS2SgyuPiKgEhqBXxkE+n4HKkNygQaqmaccu12mYyRwzCNA9p94K8KEV18Ch4OwDK4RQUNIZWQNYaGSSsLVnVVbE+JMDoHsqQUkbXKJBQh9YrkJBn00AHxQtKOSVgEYzYjpj/sI3p73A0N2RR+38hhvAvf6RWW4YX4m+8E7YnbvpB6AYanKyLCHQAMMiM/gKGHpHLvFwUCnDpG/BVkSONoSyElaidp7brvOIMxgTpWCYE3FvwSpurTODSSiXOBbeQoyM4OjqF3Ezqb0UTS9Dvzmdw88lBJvJwRMyQwI4t52OiHo5IuoxQ9HUB9oHqYowubFGYxX/hKXmOPtiJJNQ4gPyf9c1s9CEBlYXY7DlfzFktyLU/F7O3nB8ldGQkMYfvW7lUwBPx9NMosz/7Gozt1UcP9Vd1FP0E822rbSvWlpWmqZhjrXCE126u9cWStzp6jt/zNMALXl7O23vVOgKg9s7kGTjy/0Vh5X2Luk8fPlj1idQdx/8=
before_install:
- echo "$GOOGLE_INTEGRATION_PASSWORD" | gpg --batch --yes --passphrase-fd 0 ./config/etcd.json.gpg
- echo "$GOOGLE_INTEGRATION_PASSWORD" | gpg --batch --yes --passphrase-fd 0 ./config/logit-io-config.json.gpg
- echo "$GOOGLE_INTEGRATION_PASSWORD" | gpg --batch --yes --passphrase-fd 0 ./config/google-travis-service-account.json.gpg
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker image build -t $PROJECT_NAME:$PROJECT_VERSION .
- docker image tag $PROJECT_NAME:$PROJECT_VERSION $DOCKER_USERNAME/$PROJECT_NAME:$PROJECT_VERSION
- docker image push $DOCKER_USERNAME/$PROJECT_NAME
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
- gcloud auth activate-service-account --key-file ./config/google-travis-service-account.json
- gcloud config set project massive-boulder-263710
- gcloud container clusters get-credentials lpp --zone us-central1-a --project massive-boulder-263710
- gcloud components install kubectl
- kubectl apply -f ./kubernetes/deployment.yaml
