apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: lpp-ingress
spec:
  rules:
    - http:
        paths:
          - path: /parser(/|$)(.*)
            backend:
              serviceName: lpp-parser-service
              servicePort: 80
          - path: /route-finder(/|$)(.*)
            backend:
              serviceName: lpp-route-finder-service
              servicePort: 81